export const ddiList = [
    { code: '55', country: 'Brasil 🇧🇷' },
    { code: '1', country: 'Estados Unidos 🇺🇸' },
    { code: '351', country: 'Portugal 🇵🇹' },
    { code: '54', country: 'Argentina 🇦🇷' },
    { code: '591', country: 'Bolívia 🇧🇴' },
    { code: '56', country: 'Chile 🇨🇱' },
    { code: '57', country: 'Colômbia 🇨🇴' },
    { code: '593', country: 'Equador 🇪🇨' },
    { code: '34', country: 'Espanha 🇪🇸' },
    { code: '33', country: 'França 🇫🇷' },
    { code: '52', country: 'México 🇲🇽' },
    { code: '595', country: 'Paraguai 🇵🇾' },
    { code: '51', country: 'Peru 🇵🇪' },
    { code: '44', country: 'Reino Unido 🇬🇧' },
    { code: '598', country: 'Uruguai 🇺🇾' },
    { code: '58', country: 'Venezuela 🇻🇪' },
    { code: '49', country: 'Alemanha 🇩🇪' },
    { code: '39', country: 'Itália 🇮🇹' },
    { code: '81', country: 'Japão 🇯🇵' },
    { code: '86', country: 'China 🇨🇳' },
    { code: '91', country: 'Índia 🇮🇳' },
    { code: '7', country: 'Rússia 🇷🇺' },
    { code: '27', country: 'África do Sul 🇿🇦' },
    { code: '244', country: 'Angola 🇦🇴' },
    { code: '258', country: 'Moçambique 🇲🇿' },
].sort((a, b) => a.country.localeCompare(b.country));
